[package]
name = "merc_lps"
description = "Explicit and symbolic state space exploration for mCRL2 linear process specifications."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
# Enabled additional metrics.
metrics = ["merc_explore/metrics", "merc_symbolic/metrics"]

# Derive the `clap::ValueEnum` trait.
clap = ["dep:clap"]

[lints]
workspace = true

[dependencies]
mcrl2.workspace = true
merc_data.workspace = true
merc_explore = { workspace = true, features = ["clap"] }
merc_io.workspace = true
merc_lts = { workspace = true, features = ["clap"] }
merc_symbolic = { workspace = true, features = ["clap"] }
merc_unsafety.workspace = true
merc_utilities.workspace = true
oxidd.workspace = true

clap = { workspace = true, optional = true }
log.workspace = true
rayon.workspace = true

[dev-dependencies]
merc_reduction.workspace = true
merc_syntax.workspace = true
tempfile.workspace = true
