name: "Copilot Setup Steps"


on:  
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml


env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

  permissions:
    contents: read

  steps:
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libfontconfig1-dev, libfreetype6-dev
        version: 1.0
      if: matrix.os == 'ubuntu-latest'

    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable

    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        submodules: true