//! These are Rust wrappers around the mCRL2 classes

mod atermpp;
mod control_flow;
mod data;
mod data_expression;
mod global_lock;
mod log;
mod lps;
mod pbes;
mod pbes_expression;
mod visitor;

pub use atermpp::ATerm;
pub use atermpp::ATermArgs;
pub use atermpp::ATermInt;
pub use atermpp::ATermIntRef;
pub use atermpp::ATermList;
pub use atermpp::ATermListIter;
pub use atermpp::ATermListIterRef;
pub use atermpp::ATermListRef;
pub use atermpp::ATermRef;
pub use atermpp::ATermSend;
pub use atermpp::ATermString;
pub use atermpp::ATermStringRef;
pub(crate) use atermpp::BfTermPool;
pub use atermpp::Markable;
pub use atermpp::Protected;
pub use atermpp::Symbol;
pub use atermpp::SymbolRef;
pub use atermpp::TermIterator;
pub use atermpp::Todo;
pub(crate) use atermpp::is_aterm_int;
pub(crate) use atermpp::is_aterm_string;
pub use atermpp::mcrl2_aterm_to_merc;
pub use atermpp::merc_aterm_to_mcrl2;

pub use mcrl2_sys::atermpp::ffi::_aterm;

pub use control_flow::CfgEdge;
pub use control_flow::CfgSummand;
pub use control_flow::CfgTarget;
pub use control_flow::ControlFlowGraph;

pub use data::DataSpecification;

pub use data_expression::DataAbstraction;
pub use data_expression::DataAbstractionRef;
pub use data_expression::DataApplication;
pub use data_expression::DataApplicationRef;
pub use data_expression::DataBinder;
pub use data_expression::DataBinderRef;
pub use data_expression::DataExpression;
pub use data_expression::DataExpressionRef;
pub use data_expression::DataFunctionSymbol;
pub use data_expression::DataFunctionSymbolRef;
pub use data_expression::DataMachineNumber;
pub use data_expression::DataMachineNumberRef;
pub use data_expression::DataUntypedIdentifier;
pub use data_expression::DataUntypedIdentifierRef;
pub use data_expression::DataVariable;
pub use data_expression::DataVariableRef;
pub use data_expression::DataWhereClause;
pub use data_expression::DataWhereClauseRef;
pub use data_expression::SortExpression;
pub use data_expression::SortExpressionRef;
pub use data_expression::is_abstraction;
pub use data_expression::is_application;
pub(crate) use data_expression::is_data_expression;
pub use data_expression::is_function_symbol;
pub use data_expression::is_machine_number;
pub use data_expression::is_untyped_identifier;
pub use data_expression::is_variable;
pub use data_expression::is_where_clause;
pub use data_expression::remove_index;
pub use data_expression::substitute_variables;

pub(crate) use global_lock::lock_global;

pub use log::set_reporting_level;
pub use log::verbosity_to_log_level;

pub use lps::LearnSuccessorsContext;
pub use lps::LinearProcessInitializer;
pub use lps::LinearProcessSpecification;
pub use lps::LinearSummand;
pub use lps::PreprocessOptions;
pub use lps::preprocess;
pub use lps::pretty_print_multi_action;
pub use lps::read_lps;
pub use lps::read_lps_text;
pub use lps::tau_multi_action;

pub use pbes::Mcrl2ControlFlowGraph;
pub use pbes::Mcrl2ControlFlowGraphVertex;
pub use pbes::Pbes;
pub use pbes::PbesEquation;
pub use pbes::PbesEquations;
pub use pbes::PbesRewriteContext;
pub use pbes::PbesStategraph;
pub use pbes::PredicateVariable;
pub use pbes::PropositionalVariable;
pub use pbes::SrfEquation;
pub use pbes::SrfPbes;
pub use pbes::SrfSummand;
pub use pbes::StategraphEquation;
pub use pbes::make_data_assignment_list;
pub use pbes::reorder_propositional_variables;
pub use pbes::substitute_data_expressions;

pub use pbes_expression::PbesAnd;
pub use pbes_expression::PbesAndRef;
pub use pbes_expression::PbesExists;
pub use pbes_expression::PbesExistsRef;
pub use pbes_expression::PbesExpression;
pub use pbes_expression::PbesExpressionRef;
pub use pbes_expression::PbesForall;
pub use pbes_expression::PbesForallRef;
pub use pbes_expression::PbesImp;
pub use pbes_expression::PbesImpRef;
pub use pbes_expression::PbesNot;
pub use pbes_expression::PbesNotRef;
pub use pbes_expression::PbesOr;
pub use pbes_expression::PbesOrRef;
pub use pbes_expression::PbesPropositionalVariableInstantiation;
pub use pbes_expression::PbesPropositionalVariableInstantiationRef;
pub use pbes_expression::is_pbes_and;
pub use pbes_expression::is_pbes_exists;
pub(crate) use pbes_expression::is_pbes_expression;
pub use pbes_expression::is_pbes_false;
pub use pbes_expression::is_pbes_forall;
pub use pbes_expression::is_pbes_imp;
pub use pbes_expression::is_pbes_not;
pub use pbes_expression::is_pbes_or;
pub use pbes_expression::is_pbes_propositional_variable_instantiation;
pub use pbes_expression::is_pbes_true;

pub use visitor::ClosureVisitor;
pub use visitor::DataExpressionContextVisitor;
pub use visitor::DataExpressionVisitor;
pub use visitor::Descend;
pub use visitor::PbesClosureVisitor;
pub use visitor::PbesConnective;
pub use visitor::PbesExpressionContextVisitor;
pub use visitor::PbesExpressionVisitor;
pub use visitor::PbesFlattenIter;
pub use visitor::PbesFlattenStack;
pub use visitor::VisitResult;
pub use visitor::flatten_associative;
pub use visitor::flatten_pbes_and_into;
pub use visitor::flatten_pbes_or_into;
pub use visitor::free_variables_data_expression;
pub use visitor::pbes_expression_pvi;
pub use visitor::try_visit_data_expr_with;
pub use visitor::try_visit_pbes_expr_with;
pub use visitor::variable_occurrences_data_expression;
pub use visitor::variable_occurrences_pbes_expression;
pub use visitor::visit_data_expr_with;
pub use visitor::visit_pbes_expr_with;
