[workspace.package]
edition = "2024"
license = "BSL-1.0"
rust-version = "1.91.0"
version = "1.0.0"

# Add debug information to the release binaries.
[profile.release]
lto = "thin"
panic = "abort"
debug = "line-tables-only"

[workspace]
resolver = "3"
members = [
    "crates/mcrl2",
    "crates/mcrl2-macros",
    "crates/merc_lps",
    "crates/merc_pbes",
    "crates/xtask",
    "lps",
    "pbes",
]
exclude = [
    "crates/mCRL2-sys",
]

[workspace.lints.rustdoc]

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
env_logger = { version = "0.11", features = ["kv"] }
itertools = "0.15"
log = { version = "0.4", features = ["kv"] }
parking_lot = "0.12"
petgraph = "0.8"
rand = "0.10"
rayon = "1.12"
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
streaming-iterator = "0.1" 
tempfile = "3.27"
test-case = "3"
thiserror = "2.0"

# Dependencies used in procedural macros.
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full"] }

# Dependencies used in xtask
duct = "1.1"
which = "8.0"

# The workspace libraries.
mcrl2 = { path = "crates/mcrl2" }
mcrl2-macros = { path = "crates/mcrl2-macros" }
mcrl2-sys = { git = "https://github.com/MERCorg/mCRL2-sys", rev = "6762cca0d03e2c17073c437ce7eadc9fc2e28024" }
merc_aterm = { path = "../../crates/aterm" }
merc_collections = { path = "../../crates/collections" }
merc_data = { path = "../../crates/data" }
merc_explore = { path = "../../crates/explore", features = ["clap"] }
merc_io = { path = "../../crates/io" }
merc_lps = { path = "crates/merc_lps" }
merc_lts = { path = "../../crates/lts", features = ["clap"] }
merc_pbes = { path = "crates/merc_pbes" }
merc_reduction = { path = "../../crates/reduction" }
merc_symbolic = { path = "../../crates/symbolic", features = ["clap"] }
merc_tools = { path = "../../crates/tools" }
merc_typecheck = { path = "../../crates/typecheck" }
merc_unsafety = { path = "../../crates/unsafety" }
merc_syntax = { path = "../../crates/syntax" }
merc_utilities = { path = "../../crates/utilities" }
merc_vpg = { path = "../../crates/vpg" }

oxidd = { version = "0.12", features = ["multi-threading"] }

# [patch."https://github.com/MERCorg/mCRL2-sys"]
# mcrl2-sys = { path = "crates/mCRL2-sys" }

[patch.crates-io]
oxidd = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }
oxidd-core = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }
oxidd-dump = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }
oxidd-reorder = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }
oxidd-rules-bdd = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }
oxidd-rules-ldd = { git = "https://github.com/mlaveaux/oxidd", rev = "c2a6d41aa8b074ca40cafb1d2e04c6ccae1c58ba" }