#![doc = include_str!("../README.md")]
#![forbid(unsafe_code)]

mod feature_transition_system;
mod parity_games;
mod priority_promotion;
mod project_fts;
mod project_vpg;
mod reachability;
mod repeat;
mod solver;
mod strategy;
mod submap;
mod symbolic;
mod translate;
mod two_sided_lifting;
mod variability_translate;
mod variability_zielonka;
mod verify;
mod zielonka;

pub(crate) use feature_transition_system::*;
pub(crate) use parity_games::*;
pub(crate) use repeat::*;
pub(crate) use strategy::*;
pub(crate) use submap::*;
pub(crate) use translate::*;
pub(crate) use zielonka::*;

pub use feature_transition_system::FeatureDiagram;
pub use feature_transition_system::read_fts;
pub use parity_games::PG;
pub use parity_games::PGBuilder;
pub use parity_games::ParityGame;
pub use parity_games::ParityGameBuilder;
pub use parity_games::ParityGameFormat;
pub use parity_games::PgDot;
pub use parity_games::Player;
pub use parity_games::PlayerVec;
pub use parity_games::Priority;
pub use parity_games::VertexIndex;
pub use parity_games::VpgDot;
pub use parity_games::guess_format_from_extension;
pub use parity_games::make_vpg_total;
pub use parity_games::random_parity_game;
pub use parity_games::read_pg;
pub use parity_games::read_vpg;
pub use parity_games::write_pg;
pub use parity_games::write_vpg;
pub use priority_promotion::solve_priority_promotion;
pub use project_fts::ProjectedLts;
pub use project_fts::project_feature_transition_system_iter;
pub use project_vpg::Projected;
pub use project_vpg::project_variability_parity_games_iter;
pub use reachability::compute_reachable;
pub use solver::Solver;
pub use solver::VpgSolver;
pub use symbolic::AttractorProgress;
pub use symbolic::ExtendedParityGame;
pub use symbolic::RecursionProgress;
pub use symbolic::SymbolicParityGame;
pub use symbolic::SymbolicSolution;
pub use symbolic::convert_symbolic_parity_game;
pub use symbolic::detect_fatal_attractors;
pub use symbolic::detect_fatal_attractors_within_safe_vertices;
pub use symbolic::detect_forced_cycles;
pub use symbolic::detect_forced_cycles_within_safe_vertices;
pub use symbolic::detect_solitair_cycles;
pub use symbolic::detect_solitair_cycles_within_safe_vertices;
pub use symbolic::encode_parity_game;
pub use symbolic::partial_solve;
pub use symbolic::solve_symbolic_zielonka;
pub use symbolic::verify_symbolic_strategy;
pub use translate::translate;
pub use two_sided_lifting::solve_two_sided_lifting;
pub use variability_translate::translate_vpg;
pub use variability_zielonka::solve_variability_product_zielonka;
pub use variability_zielonka::solve_variability_zielonka;
pub use variability_zielonka::verify_variability_product_zielonka_solution;
pub use verify::verify_solution;
pub use zielonka::Set;
pub use zielonka::solve_zielonka;
